server:
  port: 8000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/practise1
    username: postgres
    password: Root@089

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
