server:
  port: 8000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/practise1
    username: postgres
    password: Root@089

  # redis config
  redis:
  host: localhost
  port: 6379

servlet:
  session:
    timeout: 30m


  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

  security:
    user:
      password: hello
      name: hello

